version: "3.3"

services:

  sandbox-gcc74:
    build:
      context: ..
      args:
        - SANDBOX_USER_UID=999
      dockerfile: ./docker/Dockerfile
    container_name: sandbox-gcc74
    image: sandbox-gcc74
    volumes:
      - ../src:/app/src
    ports:
      - "9002:9002"
    networks:
      - docker_localhost
    environment:
      - SANDBOX_USER_UID=999
    restart: on-failure

networks:
  docker_localhost:
    external: true