version: "3.3"

services:

  sandbox-gcc74:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: sandbox-gcc74
    image: sandbox-gcc74
    volumes:
      - ../src:/app/src:ro
    ports:
      - "9002:9002"
    networks:
      - docker_localhost
    restart: on-failure

networks:
  docker_localhost:
    external: true